//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechInventory._src.database
{
    using System;
    using System.Collections.Generic;
    using TechInventory._src.pages.employees;

    public partial class EquipmentHistory
    {
        public int ID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Equipment Equipment { get; set; }
        public bool IsNew { get; internal set; }
        public Employees AssignedEmployee { get; internal set; }
        public Equipment AssignedEquipment { get; internal set; }
        internal RowState State { get; set; }
    }
}
