//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechInventory._src.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentHistory = new HashSet<EquipmentHistory>();
        }
    
        public int ID { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentType { get; set; }
        public Nullable<int> Count { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentHistory> EquipmentHistory { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
